
name: GitHub action demo
on: 
  push:
    branches:
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github
        uses: actions/checkout@v4

      - name: Build server docker image
        run: docker build -t server-image -f server/server.Dockerfile  server/
      
      - name: Build client docker image
        run: docker build -t streamlit-client -f ui/client.Dockerfile ui/
 

  

