
name: GitHub action demo
on: 
  push:
    branches:
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t client-server-image .
 

  

